package com.softtek.acceleo.demo.domain;

public enum AuthorityName {
	ROLE_USER, ROLE_ADMIN, ROLE_ANONYMOUS,

	ROLE_AFILIADOCREATE, ROLE_AFILIADOSEARCH, ROLE_AFILIADOUPDATE, ROLE_AFILIADODELETE, ROLE_BENEFICIARIOCREATE, ROLE_BENEFICIAROSEARCH, ROLE_BENEFICIARIOUPDATE, ROLE_BENEFICIARIODELETE,

	ROLE_TIPOPENSIONCREATE, ROLE_TIPOPENSIONSEARCH, ROLE_TIPOPENSIONUPDATE, ROLE_TIPOPENSIONDELETE
}